version: '3.9'
services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    depends_on:
      - pyroscope

  pyroscope:
    image: 'grafana/pyroscope:latest'
    ports:
      - 4040:4040

  demo:
    image: 'nqminhdl/demo-app:0.0.1'
    ports:
      - 6060:6060
    depends_on:
      - pyroscope

  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent/config:/etc/agent-config
    command:
      - run
      - /etc/agent-config/config.river
      - --server.http.listen-addr=0.0.0.0:12345
    environment:
      HOSTNAME: agent
      AGENT_MODE: flow
    ports:
      - "12345:12345"
    depends_on:
      - pyroscope
